---
title: "Protest and Government Crisis"
author: "Conor Cunningham"
description: "Correlation between civic unrest and government crisis"
output:
  distill::distill_article:
    self_contained: false
---





##Does the amount of anti government protests correlate with the number of government crisis? From first glance it would seem that this would be the logical assumtion. I want to determine if this is really the case. I will use the data set "Political Violence" to determine this. My two variables will be "govtcrisis =  Major Government Crises: Any rapidly developing situation" and "agovdem = antigovernment demonstrations." If it is indeed the case, I would like to know to what extent they are corelated. How much does the quantity of anti-government demonstrations corelate with the quantity of government crisisis. I hypothesis that the amount of anti-government crisis WILL correlate with an increase in the amount anti-government protests. Therefore this will be a positive regression with the number of anti-government protests being the dependent variable and the number of government crisis being the independent variable. To prove this I will look to see if there is a greater number of government crisis when there is an increase in the amount of anti-government protests. The data set is made up of 208 identified government structures indicated by "country." For each variable there are also three data sets divided by year and I will look at all three (60's,70's,80,s) together. 


EXAMPLE:
I am interested in exploring data related to immigration enforcement and immigration preferences. A working project with Asya Magazinnik (Massachusetts Institute of Technology) explores how county-level compliance of Sheriff's offices with ICE detainer requests relates to ideal point estimates of immigration preferences. Specifically: our project asks whether the public's immigration preferences, restrictive or accommodating, influences how local law enforcement agencies comply with bureaucratic delegation from ICE.

To investigate this relationship, we are relying on data from three different sources:

1. [Transactional Records Access Clearinghouse (TRAC)](https://trac.syr.edu/immigration/) data on detainer requests sent to county Sheriff's offices from the Department of Homeland Security's sub-agency Immigration Customs and Enforcement (ICE);

2. [Coooperative Election Study (CES)](https://cces.gov.harvard.edu/) data on immigration policy preferences; and

3. novel data of county-level Sheriff elections and electoral type--partisan or non-partisan elections, non-electoral appointment.

TRAC data provides us with our outcome variable, the proportion of ICE detainer requests that are complied with; CES data provides us with our explanatory variable, public immigration policy preferences; and the Sheriff electoral data provides us with a grouping variable.



